### ISSUE TITLE
Error on processing new event

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdptools#152]
```
root@401d79f18c79:/home# cat exception_log_be1d2849-57cb-4cde-977f-00fadaa2c5bf.err 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cdptools/pipelines/event_gather_pipeline.py", line 360, in process_event
    event_details = self.task_parse_and_upload_constructed_event(event)
  File "/usr/local/lib/python3.7/dist-packages/cdptools/pipelines/event_gather_pipeline.py", line 276, in task_parse_and_upload_constructed_event
    legistar_event_item_id=m_item["legistar_event_item_id"]
  File "/usr/local/lib/python3.7/dist-packages/cdptools/databases/cloud_firestore_database.py", line 506, in get_or_upload_minutes_item
    "created": datetime.utcnow()
  File "/usr/local/lib/python3.7/dist-packages/cdptools/databases/cloud_firestore_database.py", line 461, in _get_or_upload_row
    expected_max_rows=1
  File "/usr/local/lib/python3.7/dist-packages/cdptools/databases/cloud_firestore_database.py", line 446, in _select_rows_with_max_results_expectation
    raise exceptions.UniquenessError(table, [pk.column_name for pk in pks], matching)
cdptools.databases.exceptions.UniquenessError: Table: minutes_item, primary keys: ['name'] not upheld. Query returned: [{'minutes_item_id': '04cb66dd-838c-4dc4-91f4-cf8b16bbd4f3', 'matter': 'Inf 1652', 'name': 'City Budget Office Overview of the 2020 Rebalancing Package', 'title': None, 'created': DatetimeWithNanoseconds(2020, 6, 28, 17, 18, 16, 617982, tzinfo=<UTC>), 'legistar_event_item_id': 73901}, {'minutes_item_id': 'f21a0dbf-27b5-41f6-85cf-8abbdbd946f8', 'matter': 'Inf 1652', 'name': 'City Budget Office Overview of the 2020 Rebalancing Package', 'title': None, 'created': DatetimeWithNanoseconds(2020, 6, 28, 17, 18, 16, 562785, tzinfo=<UTC>), 'legistar_event_item_id': 73901}]
```

**Comment by JacksonMaxfield** [comment]
Resolved by removing duplicate minutes item then clearing all bugged event references from db.

Duplicate minutes item id found from looking in exception log.

```python
from cdptools.databases.cloud_firestore_database import CloudFirestoreDatabase

db = CloudFirestoreDatabase(credentials_path="some_file.json")
db._root.collection("minutes_item").document("some-minutes-item-id").delete()
```

Run the delete events script with bugged events, retrigger pipeline.
