### ISSUE TITLE
Missing Event: https://video.seattle.gov/media/council/sus_091719_2531937V.mp4

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdptools#77]
**Link to Source Video:** https://video.seattle.gov/media/council/sus_091719_2531937V.mp4

**SHA Key:** 62d3fbfd5f68ddbe55dfa1274d5db40d2690e3f4cace9ddccfa664bf4b7bacaa

**Traceback:**
```
Traceback (most recent call last):
  File "/home/cdptools/cdptools/pipelines/event_gather_pipeline.py", line 140, in task_transcript_get_or_create
    main_transcript_uri = self.file_store.get_file_uri(filename=tmp_ts_sentences_transcript_filepath)
  File "/home/cdptools/cdptools/file_stores/gcs_file_store.py", line 86, in get_file_uri
    return self._get_file_uri_with_creds(filename)
  File "/home/cdptools/cdptools/file_stores/gcs_file_store.py", line 66, in _get_file_uri_with_creds
    raise FileNotFoundError(filename)
FileNotFoundError: 62d3fbfd5f68ddbe55dfa1274d5db40d2690e3f4cace9ddccfa664bf4b7bacaa_ts_sentences_transcript_0.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdptools/cdptools/pipelines/event_gather_pipeline.py", line 144, in task_transcript_get_or_create
    main_transcript_uri = self.file_store.get_file_uri(filename=tmp_ts_words_transcript_filepath)
  File "/home/cdptools/cdptools/file_stores/gcs_file_store.py", line 86, in get_file_uri
    return self._get_file_uri_with_creds(filename)
  File "/home/cdptools/cdptools/file_stores/gcs_file_store.py", line 66, in _get_file_uri_with_creds
    raise FileNotFoundError(filename)
FileNotFoundError: 62d3fbfd5f68ddbe55dfa1274d5db40d2690e3f4cace9ddccfa664bf4b7bacaa_ts_words_transcript_0.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdptools/cdptools/pipelines/event_gather_pipeline.py", line 149, in task_transcript_get_or_create
    main_transcript_uri = self.file_store.get_file_uri(filename=tmp_raw_transcript_filepath)
  File "/home/cdptools/cdptools/file_stores/gcs_file_store.py", line 86, in get_file_uri
    return self._get_file_uri_with_creds(filename)
  File "/home/cdptools/cdptools/file_stores/gcs_file_store.py", line 66, in _get_file_uri_with_creds
    raise FileNotFoundError(filename)
FileNotFoundError: 62d3fbfd5f68ddbe55dfa1274d5db40d2690e3f4cace9ddccfa664bf4b7bacaa_raw_transcript_0.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 81, in _done_or_raise
    raise _OperationNotComplete()
google.api_core.future.polling._OperationNotComplete

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 101, in _blocking_poll
    retry_(self._done_or_raise)()
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/retry.py", line 202, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 4000.0s exceeded while calling functools.partial(<bound method PollingFuture._done_or_raise of <google.api_core.operation.Operation object at 0x7f08747cc898>>), last exception: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdptools/cdptools/pipelines/event_gather_pipeline.py", line 298, in process_event
    transcript_file_details, confidence = self.task_transcript_get_or_create(key, audio_uri, phrases)
  File "/home/cdptools/cdptools/pipelines/event_gather_pipeline.py", line 164, in task_transcript_get_or_create
    timestamped_sentences_save_path=tmp_ts_sentences_transcript_filepath,
  File "/home/cdptools/cdptools/sr_models/google_cloud_sr_model.py", line 90, in transcribe
    response = operation.result(timeout=4000)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 122, in result
    self._blocking_poll(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/google/api_core/future/polling.py", line 104, in _blocking_poll
    "Operation did not complete within the designated " "timeout."
concurrent.futures._base.TimeoutError: Operation did not complete within the designated timeout.
```

**Comment by JacksonMaxfield** [comment]
Was picked up during last weekend's extended collection run:

https://firebasestorage.googleapis.com/v0/b/cdp-seattle.appspot.com/o/62d3fbfd5f68ddbe55dfa1274d5db40d2690e3f4cace9ddccfa664bf4b7bacaa_ts_sentences_transcript_0.json?alt=media&token=63187d2d-797b-48d2-a817-bada5ce5dfb8
